# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Commitlint

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  commitlint:
    runs-on: ubuntu-latest
    name: Commitlint

    steps:
      # Checkout the code to access the repository files
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Node.js to install dependencies (optional if you want local commitlint config)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Choose the appropriate Node.js version

      # Install commitlint and commitlint config (if needed)
      - name: Install commitlint and dependencies
        run: |
          npm install --save-dev @commitlint/config-conventional @commitlint/cli

      # Run commitlint
      - name: Run commitlint
        run: |
          npx commitlint --from=HEAD~1 --to=HEAD
